openapi: 3.0.0
info:
  title: Football Standings Service
  version: 1.0.0
  description: A microservice to retrieve football team standings.
servers:
  - url: http://localhost:8080
paths:
  /api/standings:
    get:
      summary: Get team standings
      description: Retrieves the standing position for a specific team in a league.
      parameters:
        - in: query
          name: countryName
          schema:
            type: string
          required: true
          description: The name of the country.
        - in: query
          name: leagueName
          schema:
            type: string
          required: true
          description: The name of the football league.
        - in: query
          name: teamName
          schema:
            type: string
          required: true
          description: The name of the football team.
      responses:
        '200':
          description: Successful response with team standing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  country_id:
                    type: string
                  country_name:
                    type: string
                  league_id:
                    type: string
                  league_name:
                    type: string
                  team_id:
                    type: string
                  team_name:
                    type: string
                  overall_league_position:
                    type: string
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                      all_league_standings:
                        type: object
                        properties:
                          href:
                            type: string
        '400':
          description: Bad request, missing parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or API dependency unavailable.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
